config/routes.rb
Rails.application.routes.draw do
  resources :products
  devise_for :users
  resources :companies
  get 'welcome/index'
  root 'companies#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company < ApplicationRecord
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :new, :update, :destroy, :create]
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :price, :fetch_data, only: [:show]
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def fetch_data
      require 'zip'
      require 'open-uri'

      cc = Company.find(params[:id])

      cases = []
      url = "https://clinicaltrials.gov/ct2/download_studies?cond=&term=&type=&rslt=&age_v=&gndr=&intr=&titles=&outc=&spons=" + cc.apiTitle + "&spons_ex=Y&lead=&id=&cntry=&state=&city=&dist=&locn=&strd_s=&strd_e="
      content = open(url)

      Zip::File.open_buffer(content) do |zipfile|
        zipfile.each do |file|
          #data = File.read(file)

          doc = Nokogiri::XML(file.get_input_stream.read)

          trial = { 'brief_title' => doc.at_css('brief_title').text,
                    'nct_id' => doc.at_css('nct_id').text,
                    'official_title' => doc.at_css('official_title').text,
                    'agency' => doc.at_css('agency').text,
                    'brief_summary' => doc.css('brief_summary textblock').text,
                    'detailed_description' => doc.css('detailed_description textblock').text,
                    'overall_status' => doc.css('overall_status').text,
                    'start_date' => doc.css('start_date').text,
                    'completion_date' => doc.css('completion_date').text,
                    'primary_completion_date' => doc.css('primary_completion_date').text,
                    'phase' => doc.css('phase').text,
                    'study_type' => doc.css('study_type').text,
                    'intervention_name' => doc.css('intervention intervention_name').text
                    }

          cases.append(trial)
        end
      end

      @trials = cases

    end



    def price
      @company = Company.find(params[:id])


      # check if google ticker is defined
      if @company.GTicker.to_s.strip.empty?

        #collect the current stockprice of a company not on google finance
        url = "https://query1.finance.yahoo.com/v7/finance/chart/" + @company.yticker + "?range=1d&interval=1m&indicators=quote&includeTimestamps=true"
        price = Faraday.get url
        price = price.body
        price = JSON.parse price
        price = price['chart']['result']
        prevClose = price[0]['meta']['previousClose']
        @lastUpdated = Time.at(price[0]['meta']['currentTradingPeriod']['post']['end']).strftime("20%y-%m-%d %H:%M")
        currPrice = price[0]['indicators']['quote'][0]['close']
        currTime = price[0]['timestamp']

        n=0
        @stockPrice = []
        @stockTime = []
        while n < currPrice.length
          if currPrice[n] == nil
          else
            @stockPrice.append(currPrice[n])
            @stockTime.append(currTime[n])
          end
          n=n+1
        end
        @stockPrice = @stockPrice[-1]
        @currTime = Time.at(@stockTime[-1]).strftime("20%y-%m-%d %H:%M")
        @change = ((@stockPrice-prevClose)/(@stockPrice)*100).round(3)
        @changeP = @stockPrice-prevClose




        time = Date.today.to_time.to_i
        time2 = time - 157680000

        #url = "https://query1.finance.yahoo.com/v7/finance/chart/" + @company.yticker + "?period1=" + time2.to_s + "&period2=" + time.to_s + "&interval=1d&indicators=quote&includeTimestamps=true"
        url = "https://query1.finance.yahoo.com/v7/finance/chart/" + @company.yticker + "?range=5y&interval=1d&indicators=quote&includeTimestamps=true"
        @stock = Faraday.get url
        @stock = @stock.body
        @stock = JSON.parse @stock
        @stock = @stock['chart']['result']
        stamps = @stock[0]['timestamp']
        openv = @stock[0]['indicators']['quote'][0]['open']
        close = @stock[0]['indicators']['quote'][0]['close']
        high = @stock[0]['indicators']['quote'][0]['high']
        low = @stock[0]['indicators']['quote'][0]['low']





        @data2 = []
        n = 0
        while n < stamps.length
          list = [stamps[n], (openv[n]), (high[n]), (low[n]), (close[n])]
          @data2.append(list)
          n = n+1
        end


        n=0
        @data3 = []
        while n < @data2.length
          if @data2[n].include?(nil)
          else
            @data3.append(@data2[n])
          end
          n = n + 1
        end

        n = 0
        while n < @data3.length
          @data3[n][0] = Time.at(@data3[n][0]).strftime("20%y-%m-%d")
          n = n+1
        end

        n = 0
        a = "["
        while n < @data3.length do
          h = "{\"date\": \"" + (@data3[n][0]).to_s + "\", \"open\": \"" + (@data3[n][1]).round(3).to_s + "\", \"high\": \"" + (@data3[n][2]).round(3).to_s + "\", \"low\": \"" + (@data3[n][3]).round(3).to_s + "\", \"close\": \"" + (@data3[n][4]).round(3).to_s + "\"}"
          a = a + h + ", "
          n = n+1
        end
        @a = a[0..-3] + "]"

      else
        url = 'http://finance.google.com/finance/info?client=ig&q=' + @company.exch + '%3A' + @company.GTicker
        @stock = Faraday.get url
        @stock = @stock.body
        @stock = @stock.lines[1..-1].join
        @stock = @stock.split.join(' ')[2..-1]
        @stock = JSON.parse @stock
        @stock = @stock[0]
        # data from google as csv for charts
        url = 'https://www.google.com/finance/getprices?q=' + @company.GTicker + '&x=' + @company.exch + '&i=86400&p=40Y&f=d,c,v,k,o,h,l&df=cpct&auto=0&ei=Ef6XUYDfCqSTiAKEMg'
        @data = Faraday.get url
        @data = @data.body

        @data = @data.lines[7..-1].join
        @data = @data.split("\n")
        @date = (@data[0][0..9]).to_i

        @data2 = @data
        @data3 = []
        n = 0
        x = 0
        set = []

        while n < @data2.length
          d = @data2[x].split(',')
          if d.length < 2
            set.append(@data2[0..x])
            @data2 = @data2[x+1..-1]
            x=0
            n=0
          else
            @data3.append(d)
            x = x+1
            n = n + 1
          end
          #@data2[x][0] = x*86400 + @date
        end


        n = 0
        x = 0
        curr_d = 0
        while n < @data3.length
          if @data3[n][0].length == 11
            @data3[n][0] = @data3[n][0][1..-1]
            curr_d = @data3[n][0].to_i
            @data3[n][0] = @data3[n][0].to_i
          else
            @data3[n][0] = @data3[n][0].to_i*86400 + curr_d
          end
          @data3[n][0] = Time.at(@data3[n][0]).strftime("20%y-%m-%d")
          n = n+1
        end

        n = 0
        a = "["
        while n < @data3.length do
          h = "{\"date\": \""+ @data3[n][0] +"\", \"open\": \""+ @data3[n][4] +"\", \"high\": \""+ @data3[n][2] +"\", \"low\": \""+ @data3[n][3] +"\", \"close\": \""+ @data3[n][1] +"\"}"
          a = a + h + ", "
          n = n+1
        end
        @a = a[0..-3] + "]"

      end

      # Monthly change
      @month = "n/a"
      if @data3[-22]
        @month = ((@data3[-1][1]).to_f-(@data3[-22][1]).to_f)/((@data3[-22][1]).to_f)*100
      end

      #weekly change
      @week = "n/a"
      if @data3[-6]
        @week = ((@data3[-1][1]).to_f-(@data3[-6][1]).to_f)/((@data3[-6][1]).to_f)*100
      end

      #year change
      @year = "n/a"
      if @data3[-250]
        @year = ((@data3[-1][1]).to_f-(@data3[-250][1]).to_f)/((@data3[-250][1]).to_f)*100
      end

      #3year change
      @tyear = "n/a"
      if @data3[-250*3]
        @tyear = ((@data3[-1][1]).to_f-(@data3[-250*3][1]).to_f)/((@data3[-250*3][1]).to_f)*100
      end

      #3year change
      @fyear = "n/a"
      if @data3[-250*5]
        @fyear = ((@data3[-1][1]).to_f-(@data3[-250*5][1]).to_f)/((@data3[-250*5][1]).to_f)*100
      end

      #year to date
      @dyear = "n/a"
      now = @data3[-1][0][5..6].to_i
      if @data3[-now*21+1]
        @dyear = ((@data3[-1][1]).to_f-(@data3[-now*21+1][1]).to_f)/((@data3[-now*21+1][1]).to_f)*100
      end
    end

    def set_company
      @company = Company.find(params[:id])
      @focus_areas = @company.focus.split(', ')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:title, :description, :focus, :logo, :ticker, :GTicker, :exch, :yticker, :apiTitle)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<div class="container-2 w-container">
<div class="compange-page">

<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

</div>
</div>

app/views/companies/new.html.erb
<div class="container-2 w-container">
<div class="compange-page">
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>
</div>
</div>

app/views/companies/show.html.erb
<div class="container-2 w-container">
<div class="compange-page">
<div class="div-block-2 w-clearfix"><img class="image" height="55" sizes="188.734375px" src="images/Genmab.svg.png" srcset="<%= @company.logo %>">

  <% if user_signed_in? %>
    <a class="button w-button" href="<%= edit_company_path(@company) %>">Edit</a>
  <% end %>
  </div>
<div class="company-main-header w-clearfix">
  <div class="div-block-3 w-clearfix">
    <h1 class="company-title"><%= @company.title %></h1>
    <% if @company.GTicker.empty? %>
      <h4 class="company-symbol">(<%= @company.yticker.split('.')[0] %>:<%= @company.yticker.split('.')[1] %>)</h4>
    <% else %>
      <h4 class="company-symbol">(<%= @company.exch %>:<%= @company.GTicker %>)</h4>
    <% end %>
    <div class="div-block-10">
      <div class="text-block-2">1 Week</div>
      <% if @week == "n/a" %>
        <div class="text-block-3"><%= @week %></div>
      <% elsif @week >= 0 %>
        <div class="text-block-3 green">+<%= @week.round(2) %>%</div>
      <% else %>
        <div class="text-block-3 red"><%= @week.round(2) %>%</div>
      <% end %>
    </div>
    <div class="div-block-10">
      <div class="text-block-2">1 Month</div>
      <% if @month == "n/a" %>
        <div class="text-block-3"><%= @month%></div>
      <% elsif @month >= 0 %>
        <div class="text-block-3 green">+<%= @month.round(2) %>%</div>
      <% else %>
        <div class="text-block-3 red"><%= @month.round(2) %>%</div>
      <% end %>
    </div>
    <div class="div-block-10">
      <div class="text-block-2">1 Year</div>
      <% if @year == "n/a" %>
        <div class="text-block-3"><%= @year %></div>
      <% elsif @year >= 0 %>
        <div class="text-block-3 green">+<%= @year.round(2) %>%</div>
      <% else %>
        <div class="text-block-3 red"><%= @year.round(2) %>%</div>
      <% end %>
    </div>
    <div class="div-block-10">
      <div class="text-block-2">3 Years</div>
      <% if @tyear == "n/a" %>
        <div class="text-block-3"><%= @tyear %></div>
      <% elsif @tyear >= 0 %>
        <div class="text-block-3 green">+<%= @tyear.round(2) %>%</div>
      <% else %>
        <div class="text-block-3 red"><%= @tyear.round(2) %>%</div>
      <% end %>
    </div>
    <div class="div-block-10">
      <div class="text-block-2">5 Years</div>
      <% if @fyear == "n/a" %>
        <div class="text-block-3"><%= @fyear %></div>
      <% elsif @fyear >= 0 %>
        <div class="text-block-3 green">+<%= @fyear.round(2) %>%</div>
      <% else %>
        <div class="text-block-3 red"><%= @fyear.round(2) %>%</div>
      <% end %>
    </div>
    <div class="div-block-10 last-info-div">
      <div class="text-block-2">Year to date</div>
      <% if @dyear == "n/a" %>
        <div class="text-block-3"><%= @dyear %></div>
      <% elsif @dyear >= 0 %>
        <div class="text-block-3 green">+<%= @dyear.round(2) %>%</div>
      <% else %>
        <div class="text-block-3 red"><%= @dyear.round(2) %>%</div>
      <% end %>
    </div>
  </div>
  <div class="div-block-4 w-clearfix">
    <div class="div-block-10 stock-price-div">
      <% if @company.GTicker.empty? %>
        <div class="stock-text text-block-2">Stock price<span id="warning" title="This particular stock might experience delayed prices. - Please look at the Last Updated tab for time accuracy.">Warning</span></div>
      <% else %>
        <div class="stock-text text-block-2">Stock price</div>
      <% end %>
      <% if @company.GTicker.empty? %>
        <div class="stock-price"> <%= @stockPrice.round(3) %></div>
      <% else %>
        <div class="stock-price"> <%= @stock['l_cur'] %></div>
      <% end %>
    </div>
    <div class="change-div">
      <div class="text-block-2">Change</div>
      <% if @company.GTicker.empty? %>
        <% if @change > 0 %>
          <div class="text-block-8 green">+<%= @change %>%</div>
        <% else %>
          <div class="text-block-8 red"><%= @change %> %</div>
        <% end %>
      <% else %>
        <% if @stock['cp'].to_f > 0 %>
          <div class="text-block-8 green"><%= @stock['cp'] %>%</div>
        <% else %>
          <div class="text-block-8 red"><%= @stock['cp'] %> %</div>
        <% end %>
      <% end %>
    </div>
    <div class="change-div">
      <div class="text-block-2">Change in price</div>
      <% if @company.GTicker.empty? %>
        <% if @changeP > 0 %>
          <div class="change-p text-block-8">+<%= @changeP.round(3) %></div>
        <% else %>
          <div class="change-p text-block-8"><%= @changeP.round(3) %></div>
        <% end %>
      <% else %>
        <div class="change-p text-block-8"><%= @stock['c'] %></div>
      <% end %>
    </div>
    <div class="change-div last-change-div">
      <div class="text-block-2">Last Updated</div>
      <% if @company.GTicker.empty? %>
        <div class="change-p text-block-8"><%= @currTime %></div>
      <% else %>
        <div class="change-p text-block-8"><%= @stock['lt'] %></div>
      <% end %>
    </div>
  </div>
</div>
<div class="div-block-11 w-clearfix">
  <div class="text-block-9">Focus area:</div>
  <% @focus_areas.each do |f| %>
    <a class="link-2" href="#"><%= f %></a>
  <% end %>
</div>
<div class="div-block-13 w-clearfix">
  <div class="div-block-12">
    <p class="paragraph-2"><%= @company.description %></p>
  </div>
  <div class="div-block-14 " id="chartdiv">
    <script type="text/javascript">
      AmCharts.makeChart("chartdiv",
        {
          "type": "serial",
          "categoryField": "date",
          "dataDateFormat": "YYYY-MM-DD",
          "theme": "default",
          "categoryAxis": {
            "parseDates": true
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true,
            "graph": "g1",
            "graphType": "line",
            "scrollbarHeight": 30
          },
          "trendLines": [],
          "graphs": [
            {
              "balloonText": "Open:<b>[[open]]</b><br>Low:<b>[[low]]</b><br>High:<b>[[high]]</b><br>Close:<b>[[close]]</b><br>",
              "closeField": "close",
              "fillAlphas": 0.9,
              "fillColors": "#7f8da9",
              "highField": "high",
              "id": "g1",
              "lineColor": "#7f8da9",
              "lowField": "low",
              "negativeFillColors": "#db4c3c",
              "negativeLineColor": "#db4c3c",
              "openField": "open",
              "title": "Price:",
              "type": "candlestick",
              "valueField": "close"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1"
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [],
          "dataProvider": <%= raw @a.as_json %>
        }
      );
    </script>
  </div>
</div>
  <hr></hr>
  <h2 class="secondary-header">Pipeline</h2>

  <table class="pipe-table">
    <tbody>
    <tr>
      <th class="pipe-h col-25">Product</th>
      <th class="pipe-h col-25">Indication</th>
      <th colspan="6" class="pipe-h col-50">Development phase</th>
    </tr>
    <tr class="gray-bg">
      <td></td>
      <td></td>
      <td class="t-u-header">I</td>
      <td class="t-u-header">I/II</td>
      <td class="t-u-header">II</td>
      <td class="t-u-header">III</td>
      <td class="t-u-header">IIII</td>
    </tr>
    <% @trials.each do |t| %>
    <tr class="body-tr">
      <td class="bg product-t"><%= t['intervention_name'] %></td>
      <td class="bg"></td>
      <% if t['phase'] == 'Phase 1' %>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"></td>
      <td class="t-phase-s"></td>
      <td class="t-phase-s"></td>
      <td class="t-phase-s"></td>
      <% end %>
      <% if t['phase'] == 'Phase 1/Phase 2' %>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"></td>
      <td class="t-phase-s"></td>
      <td class="t-phase-s"></td>
      <% end %>
      <% if t['phase'] == 'Phase 2' %>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"></td>
      <td class="t-phase-s"></td>
      <% end %>
      <% if t['phase'] == 'Phase 3' %>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"></td>
      <% end %>
      <% if t['phase'] == 'Phase 4' %>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"><div class="green-field"></div></td>
      <td class="t-phase-s"></td>
      <% end %>
    </tr>
      <div class="pipeline-wrap">
        <div class="title-wrap">
          <h5><%= t['brief_title'] %></h5>
        </div>
        <div class="pipe-info">
          <p class="inline-p right-margin-s">Start date: <%= t['start_date'] %></p>
          <p class="inline-p">Anticipated completion date: <%= t['completion_date'] %></p>
        </div>
          
          <p><%= t['brief_summary'] %></p>
          <p>Current phase: <b><%= t['phase'] %></b></p>
          <hr>
      </div>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Back', companies_path %>
</div>
</div>

app/views/companies/show_old.html.erb
<script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
<script src="tippy.js"></script>
<div class="page">
  <p id="notice"><%= notice %></p>
  <div class="wrap">
    <img src="<%= @company.logo %>" class="clogo" />
    <br/>
    <hr>
    <div class="row info-row">
      <div class="col-md-6">
        <h1><%= @company.title %></h1>
        <% if @company.GTicker.empty? %>
          <h4>(<%= @company.yticker.split('.')[0] %>:<%= @company.yticker.split('.')[1] %>)</h4>
        <% else %>
          <h4>(<%= @company.exch %>:<%= @company.GTicker %>)</h4>
        <% end %>
        <table class="info-t c-t">
          <tr>
            <th>1 Week</th>
            <th>1 Month</th>
            <th>1 Year</th>
            <th>3 Year</th>
            <th>5 Year</th>
            <th>Year to date</th>
          </tr>
          <tr>
            <% if @week == "n/a" %>
              <td class="t-change"><%= @week %></td>
            <% elsif @week >= 0 %>
              <td class="t-change green">+<%= @week.round(2) %>%</td>
            <% else %>
              <td class="t-change red"><%= @week.round(2) %>%</td>
            <% end %>

            <% if @month == "n/a" %>
              <td class="t-change"><%= @month%></td>
            <% elsif @month >= 0 %>
              <td class="t-change green">+<%= @month.round(2) %>%</td>
            <% else %>
              <td class="t-change red"><%= @month.round(2) %>%</td>
            <% end %>

            <% if @year == "n/a" %>
              <td class="t-change"><%= @year %></td>
            <% elsif @year >= 0 %>
              <td class="t-change green">+<%= @year.round(2) %>%</td>
            <% else %>
              <td class="t-change red"><%= @year.round(2) %>%</td>
            <% end %>

            <% if @tyear == "n/a" %>
              <td class="t-change"><%= @tyear %></td>
            <% elsif @tyear >= 0 %>
              <td class="t-change green">+<%= @tyear.round(2) %>%</td>
            <% else %>
              <td class="t-change red"><%= @tyear.round(2) %>%</td>
            <% end %>

            <% if @fyear == "n/a" %>
              <td class="t-change"><%= @fyear %></td>
            <% elsif @fyear >= 0 %>
              <td class="t-change green">+<%= @fyear.round(2) %>%</td>
            <% else %>
              <td class="t-change red"><%= @fyear.round(2) %>%</td>
            <% end %>

            <% if @dyear == "n/a" %>
              <td class="t-change"><%= @dyear %></td>
            <% elsif @dyear >= 0 %>
              <td class="t-change green">+<%= @dyear.round(2) %>%</td>
            <% else %>
              <td class="t-change red"><%= @dyear.round(2) %>%</td>
            <% end %>

          </tr>
        </table>
      </div>
      <div class="col-md-6 price-info">
        <table class="info-t">
          <tr>
          <% if @company.GTicker.empty? %>
            <th>Stock price <span id="warning" title="This particular stock might experience delayed prices. - Please look at the Last Updated tab for time accuracy.">Warning</span></th>
          <% else %>
            <th>Stock price</th>
          <% end %>
          </tr>
          <tr>
            <% if @company.GTicker.empty? %>
              <td class="t-price"> <%= @stockPrice.round(3) %></td>
            <% else %>
              <td class="t-price"> <%= @stock['l_cur'] %></td>
            <% end %>
            
          </tr> 
        </table>
        <table class="info-t">
          <tr>
            <th>Change</th>
            <th>Change in price</th>
            <th>Last updated</th>
          </tr>
          <tr>
            <% if @company.GTicker.empty? %>
              <% if @change > 0 %>
                <td class="t-mcap green"><%= @change %>%</td>
              <% else %>
                <td class="t-mcap red"><%= @change %> %</td>
              <% end %>
            <% else %>
              <% if @stock['cp'].to_f > 0 %>
                <td class="t-mcap green"><%= @stock['cp'] %>%</td>
              <% else %>
                <td class="t-mcap red"><%= @stock['cp'] %> %</td>
              <% end %>
            <% end %>
            
            <% if @company.GTicker.empty? %>
              <% if @changeP > 0 %>
                <td class="t-mcap">+<%= @changeP.round(3) %></td>
              <% else %>
                <td class="t-mcap"><%= @changeP.round(3) %></td>
              <% end %>
              <td class="t-mcap"><%= @currTime %></td>
            <% else %>
              <td class="t-mcap"><%= @stock['c'] %></td>
              <td class="t-mcap"><%= @stock['lt'] %></td>
            <% end %>
            
          </tr>
        </table>
      </div>
    </div>
    <hr>
    <div class="row">
      <div class="col-md-12 focus-area">
        <h4><b>Focus area</b>: <%= @company.focus %></h4>
      </div>
    </div>
    <div class="row">
    <div class="col-md-5">
      <p><%= @company.description %></p>
    </div>
    <div class="col-md-7 c-chart" id="chartdiv">
      <!-- amCharts javascript code -->
    <script type="text/javascript">
      AmCharts.makeChart("chartdiv",
        {
          "type": "serial",
          "categoryField": "date",
          "dataDateFormat": "YYYY-MM-DD",
          "theme": "default",
          "categoryAxis": {
            "parseDates": true
          },
          "chartCursor": {
            "enabled": true
          },
          "chartScrollbar": {
            "enabled": true,
            "graph": "g1",
            "graphType": "line",
            "scrollbarHeight": 30
          },
          "trendLines": [],
          "graphs": [
            {
              "balloonText": "Open:<b>[[open]]</b><br>Low:<b>[[low]]</b><br>High:<b>[[high]]</b><br>Close:<b>[[close]]</b><br>",
              "closeField": "close",
              "fillAlphas": 0.9,
              "fillColors": "#7f8da9",
              "highField": "high",
              "id": "g1",
              "lineColor": "#7f8da9",
              "lowField": "low",
              "negativeFillColors": "#db4c3c",
              "negativeLineColor": "#db4c3c",
              "openField": "open",
              "title": "Price:",
              "type": "candlestick",
              "valueField": "close"
            }
          ],
          "guides": [],
          "valueAxes": [
            {
              "id": "ValueAxis-1"
            }
          ],
          "allLabels": [],
          "balloon": {},
          "titles": [],
          "dataProvider": <%= raw @a.as_json %>
        }
      );
    </script>
    </div>
    <script>
    tippy('#warning', {arrow: true})
    </script>
    <hr>
    </div>
    <hr>
    <%= link_to 'Edit', edit_company_path(@company) %> |
    <%= link_to 'Back', companies_path %>
  </div>
</div>